### ISSUE TITLE
Toevoegen alle codegorillas aan github

### ISSUE THREAD

**Issue by rschoemaker12** [codeGorillaNL/Website#7]
Een aantal mensen zijn nog niet toegevoegd aan Github. hebben of nog geen account of nog geen invite

**Comment by codeZillaNL** [comment]
Jullie zitten in de verkeerde repository, deze is bedoeld voor de website (codegorilla.nl).
Ik heb een nieuwe aangemaakt voor codeMatch:
[https://github.com/codeGorillaNL/codeMatch](url)
