### ISSUE TITLE
aproval clean code

### ISSUE THREAD

**Issue by rschoemaker12** [codeGorillaNL/Website#8]
Could you review and if necessary edit this document. If you approve it we would al know what rules for clean code to use.  We might need some explanation what the rules exactly mean. They are from the book Clean code by Robert C. Martin.

**Comment by rschoemaker12** [comment]
Document is now also in wiki

**Comment by Bijbrengen** [comment]
The wiki document has been changed and approved. Please remove it as a branch of the master. Branches are not meant for documentation, but for versions of the master.

**Comment by rschoemaker12** [comment]
rules are in wikki
